### ISSUE TITLE
TSC offset code is broken

### ISSUE THREAD

**Issue by blitz** [TUD-OS/NUL#9]
tsc_off is used in vcpu.cc (handle_rdtsc, handle_wrmsr) after it is destroyed by TSC drift compensation.

**Comment by blitz** [comment]
(Patch is in the pipe.)

**Comment by udosteinberg** [comment]
The semantics of the TSC offset field in the UTCB (which is a negative number that is added to the HW TSC to form the virtual TSC value) are as follows:
- Reads of TSC offset into the UTCB return the value of the TSC offset from the VMCS/VMCB. So, from the VMM perspective, the inbound TSC offset is **absolute**.
- Writes to the TSC offset **add** the value from the UTCB to the TSC offset in the VMCS/VMCB. So, from the VMM perspective, the outbound TSC offset is **relative**.

_Rationale_: We cannot let the VMM set an outbound absolute value for the TSC offset, because between the moment when the VMM computes its desired absolute TSC offset value and the moment when that value would be written into the VMCS/VMCB, the vCPU could be preempted (while still in the VMM), which would cause a TSC offset adjustment for the vCPU in the hypervisor. That adjustment would be lost if we subsequently stored the absolute value, which the VMM previously computed.

**Comment by blitz** [comment]
I hope you didn't write that for me. ;-) You should probably drop this text block into the spec. It currently doesn't mention any of this (at least I couldn't find it right now when looking for "TSC" and "offset").
